USE CALLCENTER

TRUNCATE TABLE StatystykaPracownicza;
TRUNCATE TABLE Polaczenie;
TRUNCATE TABLE Agent;
TRUNCATE TABLE Czas;
TRUNCATE TABLE Data;
TRUNCATE TABLE Dzial;
TRUNCATE TABLE Klient;
TRUNCATE TABLE PoPremii;
TRUNCATE TABLE Producent;
TRUNCATE TABLE Produkt;
TRUNCATE TABLE Rezultat;

